import axios, { AxiosResponse } from 'axios';

const options = {
  method: 'GET',
  url: 'https://jsearch.p.rapidapi.com/search',
  params: {
    query: 'React developer in Texas, USA',
    page: '1',
    num_pages: '1',
  },
  headers: {
    'X-RapidAPI-Key': '27223bcef7mshbae63b05a22a14fp155a25jsn44bb28edc602',
    'X-RapidAPI-Host': 'jsearch.p.rapidapi.com',
  },
};

export const fetchJobs = async () => {
  try {
    const response = await axios.request(options);
    return { response, error: false };
  } catch (error) {
    return { data: null, error: true };
  }
};
// const logFetchProducts = async () => {
//   const result = await fetchProducts();
//   console.log("result",result);
// };

// logFetchProducts();

const data = [
  {
    job_id: '70TAzH8W_MHzd5k5AAAAAA==',
    employer_name: 'Magnus Technology Solutions',
    employer_logo:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6jDxj9ijK5FI1q7aYX2LJr7YxTpzqyPhX_-tp&s=0',
    employer_website: 'http://www.magnustechnol.com',
    employer_company_type: null,
    job_publisher: 'ZipRecruiter',
    job_employment_type: 'FULLTIME',
    job_title: 'Python Developer Entry level',
    job_apply_link:
      'https://www.ziprecruiter.com/c/Magnus-Technology-Solutions/Job/Python-Developer-Entry-level/-in-Dallas,TX?jid=fd404ba337347616',
    job_apply_is_direct: true,
    job_apply_quality_score: 0.7118,
    apply_options: [
      {
        publisher: 'ZipRecruiter',
        apply_link:
          'https://www.ziprecruiter.com/c/Magnus-Technology-Solutions/Job/Python-Developer-Entry-level/-in-Dallas,TX?jid=fd404ba337347616',
        is_direct: true,
      },
      {
        publisher: 'Core Soft Technologies Careers',
        apply_link:
          'https://coresoftwaretech.betterteam.com/python-developer-%28-entrylevel-%29',
        is_direct: true,
      },
      {
        publisher: 'Monster',
        apply_link:
          'https://www.monster.com/job-openings/python-developer-entry-level-san-jose-ca--769e5a30-093e-4d5f-a63b-f6a7715be2b2',
        is_direct: true,
      },
    ],
    job_description:
      'We are seeking a Python Developer Entry Level to become an integral part of our team! You will be responsible for creating and modifying computer application software or specialized utility programs.\n\nResponsibilities:\n• Analyze user needs and develop software solutions\n• Work with project manager or product owner to meet specification needs\n• Recommend software upgrades to optimize operational efficiency\n• Collaborate with other developers to design and optimize code\n• Create flowcharts and user guides for new and existing programs\n• Document all programming tasks and procedures\n• Perform routine software maintenance\n\nQualifications:\n• Previous experience in software development, computer engineering, or other related fields\n• Knowledge of Java, Python, or other programming languages\n• Familiarity with relational databases such as MySQL, Oracle, and SQL Server\n• Deadline and detail-oriented\n• Strong analytical and critical thinking skills\n\nCompany DescriptionMagnus Technology Solutions provide quick orientation / training for professionals & placement for candidates having work authorization in USA. We work on #Selenium, #QA_Testing, #QA_Automation, #Manual_Testing #Dotnet, #java, #j2ee, #java_UI, #Angular, #React, #Python, #DevOps, #Salesforce, #Hadoop, #IOS, #Android, #RPA, #Mulesoft and any #Developer related #Technologies.',
    job_is_remote: true,
    job_posted_at_timestamp: 1715801391,
    job_posted_at_datetime_utc: '2024-05-15T19:29:51.000Z',
    job_city: 'Dallas',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 32.776665,
    job_longitude: -96.79699,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs&htidocid=70TAzH8W_MHzd5k5AAAAAA%3D%3D#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=70TAzH8W_MHzd5k5AAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2024-06-26T00:00:00.000Z',
    job_offer_expiration_timestamp: 1719360000,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 80000,
    job_max_salary: 100000,
    job_salary_currency: 'USD',
    job_salary_period: 'YEAR',
    job_highlights: {
      Qualifications: [
        'Previous experience in software development, computer engineering, or other related fields',
        'Knowledge of Java, Python, or other programming languages',
        'Familiarity with relational databases such as MySQL, Oracle, and SQL Server',
        'Deadline and detail-oriented',
        'Strong analytical and critical thinking skills',
        'Company DescriptionMagnus Technology Solutions provide quick orientation / training for professionals & placement for candidates having work authorization in USA',
      ],
      Responsibilities: [
        'You will be responsible for creating and modifying computer application software or specialized utility programs',
        'Analyze user needs and develop software solutions',
        'Work with project manager or product owner to meet specification needs',
        'Recommend software upgrades to optimize operational efficiency',
        'Collaborate with other developers to design and optimize code',
        'Create flowcharts and user guides for new and existing programs',
        'Document all programming tasks and procedures',
        'Perform routine software maintenance',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113200',
    job_onet_job_zone: '4',
    job_occupational_categories: [
      '15-1132.00: Software Developers, Applications',
    ],
    job_naics_code: null,
    job_naics_name: null,
  },
  {
    job_id: '7oKm_SkxjLxpFtVuAAAAAA==',
    employer_name: 'SynergisticIT',
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: 'ZipRecruiter',
    job_employment_type: 'FULLTIME',
    job_title: 'PYTHON DEVELOPER(ENTRY LEVEL)',
    job_apply_link:
      'https://www.ziprecruiter.com/c/SynergisticIT/Job/PYTHON-DEVELOPER(ENTRY-LEVEL)/-in-Austin,TX?jid=95b95b82c4f3b4bd',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5894,
    apply_options: [
      {
        publisher: 'ZipRecruiter',
        apply_link:
          'https://www.ziprecruiter.com/c/SynergisticIT/Job/PYTHON-DEVELOPER(ENTRY-LEVEL)/-in-Austin,TX?jid=95b95b82c4f3b4bd',
        is_direct: false,
      },
    ],
    job_description:
      "SynergisticIT is committed to fast track your career by increasing your career prospects. We provide a broad spectrum of career advancement solutions. Whether you are struggling to find a job or hustling to get noticed by the hiring managers, we can help you stand out in your professional endeavors.\nTrusted by thousands of tech enthusiasts, SynergisticIT can bridge your skill and knowledge gap to make you competent for high-tech jobs. Our invaluable business acumen helps us assist thriving job seekers in achieving their career goals.\nCurrently, we are looking for adept entry-level Python Developers to work with our elite group of clients, namely Client, PayPal, Expedia Group, Google, Apple, Cognizant, Ford, Cisco, Walmart Labs, etc.\n\nRequired Qualifications and Background\n• Bachelor's degree or Master's degree in Computer Science, Electrical Engineering, Computer Engineering, Information Systems, IT, Mathematics,\n• Mathematics or Statistics background\nSkills Required\n• 0 to 2 years of experience in Python development\n• Deep understanding of the software development life cycle\n• Knowledge of Linear Algebra, Statistics, and Mathematics concepts\n• Excellent written and verbal communication skills\n• Technically inquisitive, self-learner, team player, and highly motivated\n• Strong work ethics and creative problem-solving abilities\n\nPreferred Skills\n• Deep Learning\n• Data visualization\n• Scala\n• NLP\n• Django\n• Roles and Responsibilities\nAs an entry-level Python Developer, you need to perform the following duties:\n• Write server-side web application logic\n• Write scalable and effective codes in Python\n• Develop backend components to boost overall application's performance\n• Executing tests and fixing bugs in applications and software\n• Implement data protection and security solutions\n• Connect applications with third-party web services\n• Support frontend developers by integrating UI elements into Python applications\n\nBenefits\n• Competitive salary\n• Flexible work schedule & part-time off\n• E-verified\n• H1B Filing\n• No relocation\n• On job technical support\n• Skill Enhancement\n• Opportunity to work with Fortune 500 Companies\n\nWho can apply?\nThis job opportunity is best suited for recent IT graduates who want to make a mark in the tech industry and upskill their IT talent. Anyone with a basic knowledge of Python programming or having some experience in building Python software solutions can apply for this position.\nNo third-party candidates or c2c candidates\n\nIf you are interested, please apply to the posting.\n\nNo phone calls please, Shortlisted candidates would be reached out.",
    job_is_remote: false,
    job_posted_at_timestamp: 1627023600,
    job_posted_at_datetime_utc: '2021-07-23T07:00:00.000Z',
    job_city: 'Austin',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs&htidocid=7oKm_SkxjLxpFtVuAAAAAA%3D%3D#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=7oKm_SkxjLxpFtVuAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2024-06-26T00:00:00.000Z',
    job_offer_expiration_timestamp: 1719360000,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Bachelor's degree or Master's degree in Computer Science, Electrical Engineering, Computer Engineering, Information Systems, IT, Mathematics,",
        'Mathematics or Statistics background',
        '0 to 2 years of experience in Python development',
        'Deep understanding of the software development life cycle',
        'Knowledge of Linear Algebra, Statistics, and Mathematics concepts',
        'Excellent written and verbal communication skills',
        'Technically inquisitive, self-learner, team player, and highly motivated',
        'Strong work ethics and creative problem-solving abilities',
        'Support frontend developers by integrating UI elements into Python applications',
      ],
      Responsibilities: [
        'As an entry-level Python Developer, you need to perform the following duties:',
        'Write server-side web application logic',
        'Write scalable and effective codes in Python',
        "Develop backend components to boost overall application's performance",
        'Executing tests and fixing bugs in applications and software',
        'Implement data protection and security solutions',
        'Connect applications with third-party web services',
      ],
      Benefits: [
        'Competitive salary',
        'Flexible work schedule & part-time off',
        'No relocation',
        'On job technical support',
        'Opportunity to work with Fortune 500 Companies',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113200',
    job_onet_job_zone: '4',
    job_occupational_categories: [
      '15-1132.00: Software Developers, Applications',
    ],
    job_naics_code: null,
    job_naics_name: null,
  },
  {
    job_id: 'YvdpgQjWGDbinEOyAAAAAA==',
    employer_name: 'Extend Information Systems Inc.',
    employer_logo:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpOSK255X2-kDEDQwIAhqbXdSrPX_29Xs4WaYT&s=0',
    employer_website: null,
    employer_company_type: null,
    job_publisher: 'LinkedIn',
    job_employment_type: 'FULLTIME',
    job_title: 'Looking for python Developer -Houston,TX- Full-time',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/looking-for-python-developer-houston-tx-full-time-at-extend-information-systems-inc-3888434864',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.724,
    apply_options: [
      {
        publisher: 'LinkedIn',
        apply_link:
          'https://www.linkedin.com/jobs/view/looking-for-python-developer-houston-tx-full-time-at-extend-information-systems-inc-3888434864',
        is_direct: false,
      },
      {
        publisher: 'ZipRecruiter',
        apply_link:
          'https://www.ziprecruiter.com/c/Release-Manger-Project-Manager-The-Dignify-Solutions/Job/Python-Developer-Houston,-TX/-in-Houston,TX?jid=9b289debd6bcc216',
        is_direct: false,
      },
      {
        publisher: 'Job Leap',
        apply_link:
          'https://www.jobleap.co.uk/job/07uf6iwt/python-developer-houston-tx',
        is_direct: false,
      },
      {
        publisher: 'WhatJobs',
        apply_link:
          'https://www.whatjobs.com/job/Python-Developer/houston/1566462864',
        is_direct: false,
      },
      {
        publisher: 'IT Tech Careers',
        apply_link:
          'https://ittechcareers.com/job/python-developer-houston-tx/',
        is_direct: false,
      },
    ],
    job_description:
      "Hi, Jobseekers,\n\nI hope you are doing well!\n\nWe have an opportunity for Python Developer with one of our clients for Houston, TX.\n\nPlease see the job details below and let me know if you would be interested in this role.\n\nIf interested, please send me a copy of your resume, contact details, availability, and a good time to connect with you.\n\nTitle: Python Developer\n\nLocation: Houston, TX\n\nTerms: Full-time\n\nJob Details\n\n5+ years' experience as Python developer.\n\nHands on experience in Django framework.\n\nStrong exposure and development experience using Time series data.\n\nRegression models (simple and more advanced techniques, linear and non-linear),\n\nTime series modelling\n\nStandard array of statistical software packages (Python, R, EViews, SAS)\n\nAzure fundamentals\n\nPower BI foundation level knowledge\n\nThanks & Regards\n\nMonika Singh\n\nExtend Information System Inc\n\nPhone:571-622-3980\n\nEmail: monika@extendinfosys.com\n\n44258 Mercure Circle, UNIT 102 A, Sterling VA, USA 20166",
    job_is_remote: false,
    job_posted_at_timestamp: 1712657448,
    job_posted_at_datetime_utc: '2024-04-09T10:10:48.000Z',
    job_city: 'Houston',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 29.760427,
    job_longitude: -95.369804,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs&htidocid=YvdpgQjWGDbinEOyAAAAAA%3D%3D#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=YvdpgQjWGDbinEOyAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2024-06-05T16:11:32.000Z',
    job_offer_expiration_timestamp: 1717603892,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "5+ years' experience as Python developer",
        'Hands on experience in Django framework',
        'Strong exposure and development experience using Time series data',
        'Power BI foundation level knowledge',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113200',
    job_onet_job_zone: '4',
    job_occupational_categories: null,
    job_naics_code: null,
    job_naics_name: null,
  },
  {
    job_id: 'zUu7xQGsS73G02pLAAAAAA==',
    employer_name: 'Dellfor Technologies',
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: 'ZipRecruiter',
    job_employment_type: 'CONTRACTOR',
    job_title: 'python developer',
    job_apply_link:
      'https://www.ziprecruiter.com/c/Dellfor-Technologies/Job/Python-Developer/-in-Texas-City,TX?jid=a179d64a86c79fc5',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.7157,
    apply_options: [
      {
        publisher: 'ZipRecruiter',
        apply_link:
          'https://www.ziprecruiter.com/c/Dellfor-Technologies/Job/Python-Developer/-in-Texas-City,TX?jid=a179d64a86c79fc5',
        is_direct: false,
      },
      {
        publisher: 'SmartRecruiters Job Search',
        apply_link:
          'https://jobs.smartrecruiters.com/DellforTechnologies/112787871-python-developer',
        is_direct: false,
      },
      {
        publisher:
          'WhatJobs United States | Jobs, Recruitment, News And Career Advice Hub',
        apply_link:
          'https://www.whatjobs.com/job/python-developer/texas-city/1566337832',
        is_direct: false,
      },
    ],
    job_description:
      "Company Description\n\nDellfor Technologies is founded by software professionals with fresh approach, and ideas empowering clients and partners in meeting the unique challenges created by transforming business needs. Our technical, domain expertise across obust solutions. We strive to prove ourselves from project inception through completion... Our technical, domain expertise across industries and process oriented approach enables clients to develop cost effective and robust solutions. We strive to prove ourselves from project inception through completion...\n\nTo succeed in the Dellfor technologies, you need exceptional connections - to the right experts, the right opportunities and the right answers. You'll find Dellfor Technologies right in the center of this ever-changing technological world - uncovering opportunities and connecting possibilities.\n\nAs a global provider of IT staffing services, Dellfor Technologies connects the very best IT professionals to great opportunities at leading companies. And we do it every single day - for both temporary and permanent assignments and across virtually all industries. We use our insight, flexibility and expanded resources to anticipate the needs of leading tech companies and help them make exceptional connections with top tech talent.\n\nJob Description\n\nROLE :Python Developer\n\nDURATION: Contract\n\nJob description\n\n5+years of experience\n\nPython will be the primary language, using which developer would perform SQL/CRUD operations in DB, file extraction/transformation/generation (CSV, XML, JSON, PDF), email integration.\n\nWorked with onsite/offshore model.\n\nExcellent communication skills (written and verbal), interpersonal skills, as well as outstanding organizational skills.\n\nAbility to work well under pressure in high stress situations with a calm demeanor.\n\nAdditional Information\n\nHighlights and benefits\n• We are a registered E verified company\n• Starting salary between $ 60,000 with regular increments\n• Free classroom skill enhancement program\n• Relocation allowance\n• Referral bonus\n• On the job support from experienced professionals in the relative field\n• Travel allowance\n• Insurance- Medical, dental, vision and 401K\n• Health Benefits through Carefirst BCBS (Blue Cross Blue Shield)\n• Company paid Life Insurance\n\nPlease respond with your resume. US Citizens and all other parties authorized to work in the US are encouraged to apply.\n\nJob Type: Contract\n\nSalary: $80,000.00 /year\n\nRequired education:\n• Bachelor's\n\nRequired experience:\n• Developer: 5-12year",
    job_is_remote: false,
    job_posted_at_timestamp: 1716633000,
    job_posted_at_datetime_utc: '2024-05-25T10:30:00.000Z',
    job_city: 'Texas City',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 29.383844,
    job_longitude: -94.9027,
    job_benefits: ['health_insurance', 'retirement_savings', 'dental_coverage'],
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs&htidocid=zUu7xQGsS73G02pLAAAAAA%3D%3D#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=zUu7xQGsS73G02pLAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2024-06-24T00:00:00.000Z',
    job_offer_expiration_timestamp: 1719187200,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        'Python will be the primary language, using which developer would perform SQL/CRUD operations in DB, file extraction/transformation/generation (CSV, XML, JSON, PDF), email integration',
        'Excellent communication skills (written and verbal), interpersonal skills, as well as outstanding organizational skills',
        'Ability to work well under pressure in high stress situations with a calm demeanor',
        "Bachelor's",
        'Developer: 5-12year',
      ],
      Benefits: [
        'Starting salary between $ 60,000 with regular increments',
        'Free classroom skill enhancement program',
        'Relocation allowance',
        'Referral bonus',
        'On the job support from experienced professionals in the relative field',
        'Travel allowance',
        'Insurance- Medical, dental, vision and 401K',
        'Health Benefits through Carefirst BCBS (Blue Cross Blue Shield)',
        'Company paid Life Insurance',
        'Salary: $80,000.00 /year',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113200',
    job_onet_job_zone: '4',
    job_occupational_categories: [
      '15-1132.00: Software Developers, Applications',
    ],
    job_naics_code: null,
    job_naics_name: null,
  },
  {
    job_id: 'sbjwkx8pql3kAOkIAAAAAA==',
    employer_name: 'OSO Ventures Inc',
    employer_logo:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYyCml6THNspXNTWR538kXWGzaAeCO-BcZJowt&s=0',
    employer_website: 'http://www.osoventuresinc.com',
    employer_company_type: null,
    job_publisher: 'LinkedIn',
    job_employment_type: 'FULLTIME',
    job_title: 'Python  Developer',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/python-developer-at-oso-ventures-inc-3928861369',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6281,
    apply_options: [
      {
        publisher: 'LinkedIn',
        apply_link:
          'https://www.linkedin.com/jobs/view/python-developer-at-oso-ventures-inc-3928861369',
        is_direct: false,
      },
      {
        publisher: 'Dallas - Americanlisted Classifieds',
        apply_link:
          'https://dallas-tx.americanlisted.com/jobs/python-developer_8996015994.html',
        is_direct: false,
      },
    ],
    job_description:
      'Hi,\n\nWe have urgent requirement of Python Developer at Remote Location.\n\nIf you are interested for this position or having suitable profile then, please share updated profile on amol1@osoventureinc.com\n\nPython Developer\n\nLocation : Remote\n\nFull Time : Remote\n\nClient Verizon.\n\nSkills.\n\n5+ Year Experience needed.\n\nStrong in python developing exp\n\nDjango.\n\nLinux',
    job_is_remote: false,
    job_posted_at_timestamp: 1716523942,
    job_posted_at_datetime_utc: '2024-05-24T04:12:22.000Z',
    job_city: 'Dallas',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 32.776665,
    job_longitude: -96.79699,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs&htidocid=sbjwkx8pql3kAOkIAAAAAA%3D%3D#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=sbjwkx8pql3kAOkIAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2024-06-05T16:12:39.000Z',
    job_offer_expiration_timestamp: 1717603959,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        '5+ Year Experience needed',
        'Strong in python developing exp',
      ],
      Benefits: ['Full Time : Remote'],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113200',
    job_onet_job_zone: '4',
    job_occupational_categories: null,
    job_naics_code: null,
    job_naics_name: null,
  },
  {
    job_id: 'ure4TvkUCk0T0fIqAAAAAA==',
    employer_name: 'SynergisticIT',
    employer_logo:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0',
    employer_website: null,
    employer_company_type: null,
    job_publisher: 'LinkedIn',
    job_employment_type: 'CONTRACTOR',
    job_title: 'Entry Level Python Developer',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/entry-level-python-developer-at-synergisticit-3833863754',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.7414,
    apply_options: [
      {
        publisher: 'LinkedIn',
        apply_link:
          'https://www.linkedin.com/jobs/view/entry-level-python-developer-at-synergisticit-3833863754',
        is_direct: false,
      },
      {
        publisher: 'Jooble',
        apply_link: 'https://jooble.org/jdp/-3296229903946859997',
        is_direct: false,
      },
      {
        publisher: 'Talent.com',
        apply_link: 'https://www.talent.com/view?id=e7788afd836a',
        is_direct: false,
      },
      {
        publisher: 'Jobgether',
        apply_link:
          'https://jobgether.com/offer/657bacd84929449570ddacef-remote-machine-learning-engineer-entry-level',
        is_direct: false,
      },
      {
        publisher: 'Salary.com',
        apply_link:
          'https://www.salary.com/job/synergisticit/entry-level-java-cloud-developer-remote/j202307121436597686509',
        is_direct: false,
      },
      {
        publisher: 'Lensa',
        apply_link:
          'https://lensa.com/job/synergisticit/anderson-in/junior-aws-developer/bf59c3330232666f66e66148f018e9b5',
        is_direct: false,
      },
    ],
    job_description:
      "SYNERGISTICIT is aware that the Job Market is Challenging because of Tech Layoffs. The Job market is flooded with hundreds and thousands of laid-off Jobseekers competing with existing Jobseekers. For entry-level Job seekers to get client interviews and jobs they need to differentiate themselves by ensuring they have exceptional skills and technologies to be noticed by clients.\n\nSince 2010 we have helped Jobseekers differentiate themselves by providing clients with candidates who have the requisite skills and experience to outperform at interviews and clients. Here at SynergisticIT We just don't focus on getting you a Job we make careers. All Positions are open for all visas and US citizens We at Synergisticit understand the problem of the mismatch between employer's requirements and Employee skills and that's why since 2010 we have helped thousands of candidates get jobs at technology clients like Apple, Google, and Paypal, western union, Client, visa, Walmart labs, etc., to name a few. We have an excellent reputation with the clients. Currently, we are looking for Entry Level Python Programmer\n\nWho Should Apply Recent Computer Science/Engineering /Mathematics/Statistics or Science Graduates looking to make their careers in IT Industry We welcome candidates with all visas and citizens to apply. We assist in filing for STEM extension and also for H1b and Green card filing to Candidates\n\nWe also offer Skill enhancement programs for candidates who are either missing skills or lacking Industry/Client experience with Projects and skills. Candidates have difficulty finding jobs or cracking interviews or want to improve their skill portfolio. If they are qualified with enough skills and have hands-on project work with clients then no need for skill enhancement.\n\nCandidates can benefit from skill enhancement if they fall into the below categories.\n\nCandidates who Lack Experience or are fresher with No actual Job experience with projects with clients who Have had a break in careers Lack Technical Competency or skills being demanded by clients Different visa candidates (Like OPT/H4EAD/L2EAD) who want to get employed and settle down in the USA please check the below links to see success outcomes of our candidates https://www.synergisticit.com/candidate-outcomes/\n\nWatch the below videos of us participating in Industry events with the Top companies in Technology at Oracle Cloud World/Oracle Java One (Las Vegas) and at Gartner Data Analytics Summit (Florida)\n\nOracle Cloud World Event (OCW) Las Vegas 2022 | SynergisticIT - YouTube https://www.youtube.com/watch?v=OAFOhcGy9Z8\n\nhttps://www.youtube.com/watch?v=EmO7NrWHkLM https://www.youtube.com/watch?v=NVBU9RYZ6UI\n\nhttps://www.youtube.com/watch?v=Yy74yvjatVg SynergisticIT at Gartner Data and Analytics Summit 2023 - YouTube\n\nhttps://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/contact-us/\n\nIf you have relevant skills and industry experience, please apply if not then candidates can opt for Skill enhancement.\n\nFor getting help with interviews please visit\n\nhttps://www.synergisticit.com/interview-questions/\n\nREQUIRED SKILLS For Java /Software Programmers\n• Bachelor's degree or Master's degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT\n• Highly motivated, self-learner, and technically inquisitive\n• Experience in programming language Java and understanding of the software development life cycle\n• Project work on the skills\n• Knowledge of Core Java, java script, C++ or software programming\n• Spring boot, Micro-services, Docker, Jenkins and REST API's experience\n• Excellent written and verbal communication skills\n\nFor data Science/Machine learning\n\nRequired Skills\n• Bachelor's degree or Master's degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT\n• Project work on the technologies needed\n• Highly motivated, self-learner, and technically inquisitive\n• Experience in the programming language Java and understanding of the software development life cycle\n• Knowledge of Statistics, SAS, Python, Computer Vision, and data visualization tools\n• Excellent written and verbal communication skills\n\nPreferred skills: NLP, Text mining, Tableau, Power BI, Time series analysis\n\nPlease understand skills and relevant experience on real-world projects are required by clients for selection even if it's a Junior or entry-level position the additional skills and Project work with hands-on experience building projects at the client site are the only way a candidate can be picked by clients. If not having the skills or hands-on project work at the client site, candidates can opt for skill enhancement to gain the required skills and project work. No third-party candidates or c2c candidates\n\nplease only apply to the posting\n\nNo phone calls, please. Shortlisted candidates would be reached out to.",
    job_is_remote: true,
    job_posted_at_timestamp: 1708768205,
    job_posted_at_datetime_utc: '2024-02-24T09:50:05.000Z',
    job_city: 'Dallas',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 32.776665,
    job_longitude: -96.79699,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs&htidocid=ure4TvkUCk0T0fIqAAAAAA%3D%3D#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=ure4TvkUCk0T0fIqAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2024-06-23T15:58:08.000Z',
    job_offer_expiration_timestamp: 1719158288,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        'REQUIRED SKILLS For Java /Software Programmers',
        "Bachelor's degree or Master's degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT",
        'Highly motivated, self-learner, and technically inquisitive',
        'Experience in programming language Java and understanding of the software development life cycle',
        'Knowledge of Core Java, java script, C++ or software programming',
        "Spring boot, Micro-services, Docker, Jenkins and REST API's experience",
        'Excellent written and verbal communication skills',
        'For data Science/Machine learning',
        'Project work on the technologies needed',
        'Knowledge of Statistics, SAS, Python, Computer Vision, and data visualization tools',
        "Please understand skills and relevant experience on real-world projects are required by clients for selection even if it's a Junior or entry-level position the additional skills and Project work with hands-on experience building projects at the client site are the only way a candidate can be picked by clients",
        'If not having the skills or hands-on project work at the client site, candidates can opt for skill enhancement to gain the required skills and project work',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113200',
    job_onet_job_zone: '4',
    job_occupational_categories: null,
    job_naics_code: null,
    job_naics_name: null,
  },
  {
    job_id: '3cfylwyhuS3UQ5AsAAAAAA==',
    employer_name: 'Cititec Talent',
    employer_logo:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTohFCMR2tCYroCZoHThvACT5WWJC6FpcUDtso&s=0',
    employer_website: null,
    employer_company_type: null,
    job_publisher: 'LinkedIn',
    job_employment_type: 'FULLTIME',
    job_title: 'Python Developer',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/python-developer-at-cititec-talent-3932150447',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6297,
    apply_options: [
      {
        publisher: 'LinkedIn',
        apply_link:
          'https://www.linkedin.com/jobs/view/python-developer-at-cititec-talent-3932150447',
        is_direct: false,
      },
      {
        publisher: 'BeBee',
        apply_link: 'https://us.bebee.com/job/162c51e1a3679b2535bde1f938e92781',
        is_direct: false,
      },
    ],
    job_description:
      "Python Application Developer\n\nHouston (hybrid 3 days in office)\n\n$150,00 - $170,000 + bonus (ranging 25-30%)\n\nJoin a Dynamic Commodities Trading Powerhouse\n\nThey are a rapidly growing commodities trading firm, transforming from a boutique player to a major industry force. Their global footprint spans the US, Europe, Africa, and Asia, and they are seeking a talented Python Application Developer to fuel their continued technological dominance.\n\nYou'll spearhead new Python-based development projects, streamlining middle and back office functions.\n\nWhat You'll Do\n• Craft and implement cutting-edge Python applications, optimising middle and back office processes.\n• Own the entire software development lifecycle: from needs gathering and system design to coding, testing, deployment, and maintenance.\n• Partner closely with business analysts and stakeholders to translate their needs into robust, scalable software solutions.\n\nIdeal Experience:\n• Extensive Python experience, adept at data manipulation and analysis with Pandas and data frames.\n• Experience building APIs with FAST API and interacting with databases using SQL.\n• Cloud-based development is ideal, particularly in AWS services.\n• Containerisation and orchestration experience in Docker and Kubernetes.\n• A minimum of 5 years in software development is a must, ideally within the commodities trading or financial services space.\n• You've demonstrably implemented solid software engineering practices in professional settings.",
    job_is_remote: false,
    job_posted_at_timestamp: 1716454268,
    job_posted_at_datetime_utc: '2024-05-23T08:51:08.000Z',
    job_city: 'Houston',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 29.760427,
    job_longitude: -95.369804,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs&htidocid=3cfylwyhuS3UQ5AsAAAAAA%3D%3D#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=3cfylwyhuS3UQ5AsAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2024-06-22T08:51:08.000Z',
    job_offer_expiration_timestamp: 1719046268,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 150000,
    job_max_salary: 170000,
    job_salary_currency: 'USD',
    job_salary_period: 'YEAR',
    job_highlights: {
      Qualifications: [
        'Extensive Python experience, adept at data manipulation and analysis with Pandas and data frames',
        'Experience building APIs with FAST API and interacting with databases using SQL',
        'Cloud-based development is ideal, particularly in AWS services',
        'Containerisation and orchestration experience in Docker and Kubernetes',
        'A minimum of 5 years in software development is a must, ideally within the commodities trading or financial services space',
        "You've demonstrably implemented solid software engineering practices in professional settings",
      ],
      Responsibilities: [
        'Craft and implement cutting-edge Python applications, optimising middle and back office processes',
        'Own the entire software development lifecycle: from needs gathering and system design to coding, testing, deployment, and maintenance',
        'Partner closely with business analysts and stakeholders to translate their needs into robust, scalable software solutions',
      ],
      Benefits: ['$150,00 - $170,000 + bonus (ranging 25-30%)'],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113200',
    job_onet_job_zone: '4',
    job_occupational_categories: null,
    job_naics_code: null,
    job_naics_name: null,
  },
  {
    job_id: 'pKi67Lsp4_7y4nTeAAAAAA==',
    employer_name: 'Diverse Lynx',
    employer_logo:
      'https://prod-file-upload-store.s3.amazonaws.com/0XyiwpDMSTG5Piomqn0K_6460b6f687080e26f1c0ba43f0fbc060.jpg',
    employer_website: 'http://www.diverselynx.com',
    employer_company_type: null,
    job_publisher: 'LinkedIn',
    job_employment_type: 'FULLTIME',
    job_title: 'Python Engineer',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/python-engineer-at-diverse-lynx-3934095481',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6286,
    apply_options: [
      {
        publisher: 'LinkedIn',
        apply_link:
          'https://www.linkedin.com/jobs/view/python-engineer-at-diverse-lynx-3934095481',
        is_direct: false,
      },
      {
        publisher: 'Monster',
        apply_link:
          'https://www.monster.com/job-openings/python-engineer-plano-tx--1a46bc43-02b1-4a04-8d1e-f472b8533ffb',
        is_direct: false,
      },
      {
        publisher: 'SimplyHired',
        apply_link:
          'https://www.simplyhired.com/job/k9NjXXnXacBjP4EDnLWol9D-nIS8in5y9YAnSRIBIkJKuYXOrfp3zg',
        is_direct: false,
      },
      {
        publisher: 'Ladders',
        apply_link:
          'https://www.theladders.com/job-listing/python-engineer-diverse-lynx-plano-tx-_v2_-7-3938849118.html',
        is_direct: false,
      },
      {
        publisher: 'BeBee',
        apply_link: 'https://us.bebee.com/job/12bfa608162075341e4452bce9fdfae0',
        is_direct: false,
      },
      {
        publisher: 'Talentify',
        apply_link:
          'https://www.talentify.io/job/python-engineer-plano-texas-diverse-lynx-24-20974',
        is_direct: false,
      },
      {
        publisher: 'Adzuna',
        apply_link: 'https://www.adzuna.com/details/4708279535',
        is_direct: false,
      },
      {
        publisher: 'Jobg8',
        apply_link:
          'https://jobs.jobg8.com/job/python-engineer-in-plano-texas-5673-27662206878F',
        is_direct: false,
      },
    ],
    job_description:
      'Title: Python Engineer\n\nDuration: Contract or Full-Time\n\nLocation: Plano, TX and Columbus, OH (Onsite)\n\nInterview mode: Video Conference/IN- Person\n\nJoining: ASAP\n\nThis is the description .\n\nJob Description\n\npython hard core development experience, familiar with ananconda or py -test, Boto 3 NumPy. Pandas. Framework like Django/Flask IAM roles, Security group, S3, Lambda, EC2, ECS, EKS Python application deployment experience in AWS(Ec2, ECS, EKS or Lambda)\n\nDiverse Lynx LLC is an Equal Employment Opportunity employer. All qualified applicants will receive due consideration for employment without any discrimination. All applicants will be evaluated solely on the basis of their ability, competence and their proven capability to perform the functions outlined in the corresponding role. We promote and support a diverse workforce across all levels in the company.',
    job_is_remote: false,
    job_posted_at_timestamp: 1716696006,
    job_posted_at_datetime_utc: '2024-05-26T04:00:06.000Z',
    job_city: 'Plano',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 33.019844,
    job_longitude: -96.69888,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs&htidocid=pKi67Lsp4_7y4nTeAAAAAA%3D%3D#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=pKi67Lsp4_7y4nTeAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2024-06-25T04:00:06.000Z',
    job_offer_expiration_timestamp: 1719288006,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        'python hard core development experience, familiar with ananconda or py -test, Boto 3 NumPy',
      ],
    },
    job_job_title: 'Engineer',
    job_posting_language: 'en',
    job_onet_soc: '15113200',
    job_onet_job_zone: '4',
    job_occupational_categories: null,
    job_naics_code: null,
    job_naics_name: null,
  },
  {
    job_id: 'Pc2Ivcauiql5YsuPAAAAAA==',
    employer_name: 'Cititec Talent',
    employer_logo:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTohFCMR2tCYroCZoHThvACT5WWJC6FpcUDtso&s=0',
    employer_website: null,
    employer_company_type: null,
    job_publisher: 'LinkedIn',
    job_employment_type: 'FULLTIME',
    job_title: 'Python Developer',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/python-developer-at-cititec-talent-3932150475',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6297,
    apply_options: [
      {
        publisher: 'LinkedIn',
        apply_link:
          'https://www.linkedin.com/jobs/view/python-developer-at-cititec-talent-3932150475',
        is_direct: false,
      },
    ],
    job_description:
      'Python Developer - Commodity Trading - Houston - Up to $170,000 + 30% Bonus + Package\n\nCititec Talent has partnered with a global commodities firm who are looking for a talented Python Developer to join their cutting-edge technology team. In this position, you will be designing, developing, and maintaining robust Python applications.\n\nYou will work closely with cross-functional teams, to design and develop systems for middle and back-office commodities trading applications. This opportunity will also play a pivotal part in contributing to the ongoing improvement and development of these applications.\n\nExperience\n• 5-10 years of development experience, preferably in financial applications\n• Strong Python required, along with experience with pandas\n• To be able to build multithreaded applications and service-oriented architecture\n• Proficiency with SQL/NoSQL databases and messaging middleware like Kafka\n• Familiarity with API-based solutions, such as FastAPI, and DevOps tools including basic AWS knowledge like Kubernetes\n• Proficient in object-oriented programming languages with strong debugging skills\n• Bachelor’s degree in Computer Science or similar certification',
    job_is_remote: false,
    job_posted_at_timestamp: 1716454554,
    job_posted_at_datetime_utc: '2024-05-23T08:55:54.000Z',
    job_city: 'Houston',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 29.760427,
    job_longitude: -95.369804,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs&htidocid=Pc2Ivcauiql5YsuPAAAAAA%3D%3D#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=Pc2Ivcauiql5YsuPAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2024-06-22T08:55:53.000Z',
    job_offer_expiration_timestamp: 1719046553,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: true,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 150000,
    job_max_salary: 170000,
    job_salary_currency: 'USD',
    job_salary_period: 'YEAR',
    job_highlights: {
      Qualifications: [
        '5-10 years of development experience, preferably in financial applications',
        'Strong Python required, along with experience with pandas',
        'To be able to build multithreaded applications and service-oriented architecture',
        'Proficiency with SQL/NoSQL databases and messaging middleware like Kafka',
        'Familiarity with API-based solutions, such as FastAPI, and DevOps tools including basic AWS knowledge like Kubernetes',
        'Proficient in object-oriented programming languages with strong debugging skills',
        'Bachelor’s degree in Computer Science or similar certification',
      ],
      Responsibilities: [
        'In this position, you will be designing, developing, and maintaining robust Python applications',
        'You will work closely with cross-functional teams, to design and develop systems for middle and back-office commodities trading applications',
        'This opportunity will also play a pivotal part in contributing to the ongoing improvement and development of these applications',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113200',
    job_onet_job_zone: '4',
    job_occupational_categories: null,
    job_naics_code: null,
    job_naics_name: null,
  },
  {
    job_id: 'iEHPUzeldSrrjg9aAAAAAA==',
    employer_name: 'Extend Information Systems Inc.',
    employer_logo:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpOSK255X2-kDEDQwIAhqbXdSrPX_29Xs4WaYT&s=0',
    employer_website: null,
    employer_company_type: null,
    job_publisher: 'LinkedIn',
    job_employment_type: 'FULLTIME',
    job_title:
      'Python Developer || Austin,TX(Onsite) || Only USC and GC Candidate',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/python-developer-austin-tx-onsite-only-usc-and-gc-candidate-at-extend-information-systems-inc-3888444116',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.7316,
    apply_options: [
      {
        publisher: 'LinkedIn',
        apply_link:
          'https://www.linkedin.com/jobs/view/python-developer-austin-tx-onsite-only-usc-and-gc-candidate-at-extend-information-systems-inc-3888444116',
        is_direct: false,
      },
    ],
    job_description:
      'Job Profile : Python Developer\n\nJob Location : Austin,TX\n\nJob Type : Python Developer\n\nNote : Only Independent US-Authorized Candidate (USC and GC)\n\nJob Description\n\nPython Programming, App Development, Django, Flask\n\nThanks & Regards,\n\nShubham\n\nIT Recruiter\n\nShubham@extendinfosys.com\n\n(571)-547-2870\n\nExtend Information System INC',
    job_is_remote: false,
    job_posted_at_timestamp: 1712657473,
    job_posted_at_datetime_utc: '2024-04-09T10:11:13.000Z',
    job_city: 'Austin',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs&htidocid=iEHPUzeldSrrjg9aAAAAAA%3D%3D#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=iEHPUzeldSrrjg9aAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2024-06-05T16:11:43.000Z',
    job_offer_expiration_timestamp: 1717603903,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {},
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '13107100',
    job_onet_job_zone: '4',
    job_occupational_categories: null,
    job_naics_code: null,
    job_naics_name: null,
  },
];
